# Pytorch Fundamentals

In [1]:
import torch
print(torch.__version__)

1.13.0+cu116


## Intro to Tensors

### Creating Tensors

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Number of dimensions
scalar.ndim

0

In [4]:
# Get tensor as python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
# 2 x 1 elements
vector.shape

torch.Size([2])

In [12]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [14]:
# Element access
MATRIX[0], MATRIX[0][1]

(tensor([7, 8]), tensor(8))

In [15]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

### Random Tensors

In [17]:
# Create a random tensor
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2568, 0.5978, 0.9523, 0.7807],
        [0.5547, 0.2306, 0.6585, 0.3990],
        [0.3644, 0.6266, 0.3447, 0.6947]])

In [18]:
random_tensor.ndim, random_tensor.shape

(2, torch.Size([3, 4]))

In [19]:
# Image tensor (H, W, C)
random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor

tensor([[[0.2145, 0.8580, 0.8309],
         [0.7046, 0.5709, 0.6060],
         [0.4445, 0.9226, 0.0846],
         ...,
         [0.5694, 0.9855, 0.8725],
         [0.0289, 0.1617, 0.3202],
         [0.6130, 0.2618, 0.0135]],

        [[0.7968, 0.8715, 0.5505],
         [0.4776, 0.3408, 0.4775],
         [0.9102, 0.7785, 0.0333],
         ...,
         [0.3702, 0.0328, 0.8809],
         [0.8391, 0.6193, 0.8942],
         [0.5117, 0.7107, 0.4270]],

        [[0.6335, 0.4528, 0.4181],
         [0.7331, 0.4974, 0.2714],
         [0.8821, 0.7140, 0.6004],
         ...,
         [0.9493, 0.8729, 0.1513],
         [0.3404, 0.0093, 0.2774],
         [0.5591, 0.4360, 0.8714]],

        ...,

        [[0.9133, 0.3336, 0.6675],
         [0.0606, 0.9666, 0.1504],
         [0.2564, 0.6605, 0.1298],
         ...,
         [0.3096, 0.0269, 0.3602],
         [0.3162, 0.7229, 0.4049],
         [0.3329, 0.3096, 0.7699]],

        [[0.6167, 0.1179, 0.6582],
         [0.0380, 0.4794, 0.1800],
         [0.

In [20]:
random_image_tensor.ndim, random_image_tensor.shape

(3, torch.Size([224, 224, 3]))

### Ones and Zeros Tensors

In [21]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones * random_tensor

tensor([[0.2568, 0.5978, 0.9523, 0.7807],
        [0.5547, 0.2306, 0.6585, 0.3990],
        [0.3644, 0.6266, 0.3447, 0.6947]])

In [26]:
# Check data types (default is float32)
ones.dtype

torch.float32

### Tensor Ranges and Tensor-like

In [27]:
# Range
torch.range(0, 10)

<ipython-input-27-46558dc8b6e0>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [32]:
one_to_ten = torch.arange(0, 10, 1)  # start, stop, step_size
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

3 Big Errors:

1. Not in right datatype
2. Not in right shape
3. Not on the right device

In [42]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # Specific datatype for tensor
                               device="cpu",  # Device tensor is on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [43]:
float_32_tensor.dtype

torch.float32

In [45]:
float_16_tensor = float_32_tensor.type(torch.half) # torch.float16
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [46]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [47]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors

In [48]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4417, 0.2109, 0.5222, 0.5465],
        [0.9320, 0.4261, 0.4044, 0.9390],
        [0.4356, 0.0331, 0.9757, 0.5638]])

In [50]:
# details
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.4417, 0.2109, 0.5222, 0.5465],
        [0.9320, 0.4261, 0.4044, 0.9390],
        [0.4356, 0.0331, 0.9757, 0.5638]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensor (Operations)

In [51]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [52]:
tensor - 100

tensor([-99, -98, -97])

In [53]:
tensor * 10

tensor([10, 20, 30])

In [54]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

In [57]:
# Element wise
tensor * tensor

tensor([1, 4, 9])

In [58]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [59]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2)) # wont work (Inner dimensions must match)

RuntimeError: ignored

In [65]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)).shape

torch.Size([3, 3])

In [64]:
torch.matmul(torch.rand(3, 5), torch.rand(5, 3))

tensor([[1.0214, 1.3476, 1.3427],
        [1.3290, 2.1581, 1.8946],
        [1.1544, 0.9836, 1.2897]])

In [67]:
torch.mm(torch.rand(3, 5), torch.rand(5, 3))  # alias for matmul

tensor([[0.4821, 1.1434, 1.1017],
        [0.6654, 0.6365, 1.1441],
        [1.3456, 1.1469, 1.7280]])

In [68]:
torch.mm(torch.rand(3, 5), torch.rand(3, 5).T)  # can use transpose to aid in mm

tensor([[0.5212, 0.9785, 0.7273],
        [0.5703, 1.2669, 1.1444],
        [0.5309, 0.5329, 0.3684]])

In [69]:
torch.mm(torch.rand(3, 5), torch.rand(3, 5).T).shape

torch.Size([3, 3])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [71]:
# Create tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [72]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [73]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [77]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [76]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Find the position min and max

In [79]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [80]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [81]:
x[x.argmin()], x[x.argmax()]

(tensor(0), tensor(90))

### Reshaping, Stacking, Squeezing, and Unsqueezing

In [83]:
# Create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [87]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [88]:
# Add an extra dimension
x_reshaped = x.reshape(9, 1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [90]:
# Change the view (shares the same memory as x)
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [91]:
# changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [93]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [94]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [99]:
# Squeeze tensor
x_reshaped.shape, x_reshaped.squeeze()

(torch.Size([9, 1]), tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [100]:
x_reshaped.squeeze().shape

torch.Size([9])

In [103]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [105]:
# Unsqueeze - add a single dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [109]:
# Permute - rearrange the dimensions
x_original = torch.rand(size=(224, 224, 3))
print(x_original.shape)

# Permute the original tensor
x_permuted = x_original.permute(2, 0, 1)
x_permuted.shape

torch.Size([224, 224, 3])


torch.Size([3, 224, 224])

### Indexing (Selecting Data from Tensors)

In [111]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [112]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [114]:
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [115]:
x[0][0][0] # most inner bracket

tensor(1)

In [116]:
# ":" select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [117]:
x[:, : , 1]

tensor([[2, 5, 8]])

In [118]:
x[:, 1, 1]

tensor([5])

In [119]:
x[0, 0, :]

tensor([1, 2, 3])

### Pytorch Tensors and NumPy

In [122]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)  # warning: when converting from nupy to pytorch, pytorch reflects numpy's default (float64)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [121]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [123]:
array = array + 1

In [124]:
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [125]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [126]:
tensor.dtype, numpy_tensor.dtype

(torch.float32, dtype('float32'))

In [127]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take random out of random)

In [129]:
rand_a = torch.rand(3, 4)
rand_b = torch.rand(3, 4)
rand_a == rand_b

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [132]:
# random but reproducible tensors
# set seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
rand_c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
rand_d = torch.rand(3, 4)
rand_c == rand_d

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Running tensors and Pytorch objects on the GPUs

In [1]:
!nvidia-smi

Tue Jan 17 14:55:57 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P8    11W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
# Check GPU access
import torch
torch.cuda.is_available()

True

In [4]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# Count number of devices
torch.cuda.device_count()

1

In [8]:
# Putting tensors (and models) on the GPU
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [7]:
# Putting tensors (and models) on the GPU
tensor = torch.tensor([1, 2, 3], device=device)

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


In [10]:
# Move back to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [11]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')